// Builds the public privacy pages from the privacy policy bundled in the
// RealUnit app (RealUnitCH/app assets/legal/privacy_policy_{de,en}.md, copied
// unchanged into legal/). The RealUnit mails link to realunit.app/privacy/ as
// the app's privacy policy, so the page text must stay word for word the app's.
//
//   node scripts/build-privacy.mjs          write public/privacy/{,en/}index.html
//   node scripts/build-privacy.mjs --check  exit 1 if the committed pages differ
//
// The converter covers exactly the Markdown the policy uses: # / ## / ###
// headings, paragraphs, "- " lists, **bold**, *italic* and a trailing
// backslash as line break. Anything else fails loudly instead of rendering
// wrong.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const PAGES = {
  de: {
    source: 'legal/privacy_policy_de.md',
    target: 'public/privacy/index.html',
    title: 'Datenschutzerklärung der RealUnit Wallet App',
    description: 'Datenschutzerklärung der RealUnit Wallet App der RealUnit Schweiz AG.',
    switchLabel: 'English',
    switchHref: '/privacy/en/',
    switchLang: 'en',
  },
  en: {
    source: 'legal/privacy_policy_en.md',
    target: 'public/privacy/en/index.html',
    title: 'Privacy Policy of the RealUnit Wallet App',
    description: 'Privacy policy of the RealUnit Wallet App of RealUnit Schweiz AG.',
    switchLabel: 'Deutsch',
    switchHref: '/privacy/',
    switchLang: 'de',
  },
};

function escapeHtml(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function inline(text) {
  let html = escapeHtml(text);
  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  if (html.includes('*')) throw new Error(`Unsupported emphasis in: ${text}`);
  return html;
}

export function markdownToHtml(markdown) {
  const blocks = markdown
    .replace(/\r\n/g, '\n')
    .trim()
    .split(/\n{2,}/);
  const out = [];
  for (const block of blocks) {
    const lines = block.split('\n');
    const heading = lines[0].match(/^(#{1,3}) (.+)$/);
    if (heading) {
      if (lines.length !== 1) throw new Error(`Heading with trailing lines: ${block}`);
      const level = heading[1].length;
      out.push(`<h${level}>${inline(heading[2])}</h${level}>`);
    } else if (lines.every((line) => line.startsWith('- '))) {
      const items = lines.map((line) => `  <li>${inline(line.slice(2))}</li>`);
      out.push(['<ul>', ...items, '</ul>'].join('\n'));
    } else if (lines.some((line) => /^(#|- |\d+\. |>|\||`)/.test(line))) {
      throw new Error(`Unsupported Markdown block: ${block}`);
    } else {
      const parts = lines.map((line, index) => {
        const breakAfter = line.endsWith('\\');
        if (breakAfter && index === lines.length - 1)
          throw new Error(`Line break at end of block: ${block}`);
        return inline(breakAfter ? line.slice(0, -1) : line) + (breakAfter ? '<br />' : '');
      });
      out.push(`<p>${parts.join(breakAfter(lines) ? '\n' : ' ')}</p>`);
    }
  }
  return out.join('\n');
}

function breakAfter(lines) {
  return lines.some((line) => line.endsWith('\\'));
}

export function renderPage(lang, markdown) {
  const page = PAGES[lang];
  const body = markdownToHtml(markdown)
    .split('\n')
    .map((line) => '      ' + line)
    .join('\n');
  return `<!doctype html>
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${page.title}</title>
  <meta name="description" content="${page.description}" />
  <meta name="theme-color" content="#1988C6" />
  <link rel="icon" type="image/svg+xml" href="/assets/favicon.svg" />
  <link rel="alternate" hreflang="${page.switchLang}" href="${page.switchHref}" />
  <!-- Generated by scripts/build-privacy.mjs from ${page.source}; do not edit by hand. -->
  <style>
    :root { --bg: #f2f6fa; --accent: #1988C6; --ink: #1a2733; --muted: #5b6b7a; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      line-height: 1.6;
      padding: clamp(16px, 4vw, 48px);
    }
    .card {
      max-width: 760px;
      margin: 0 auto;
      background: #fff;
      border: 1px solid #e2e8f0;
      border-radius: 18px;
      padding: clamp(24px, 5vw, 48px);
    }
    header { display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-bottom: 28px; }
    .logo { display: block; height: 40px; width: auto; }
    .lang-switch { color: var(--accent); font-weight: 600; text-decoration: none; }
    .lang-switch:hover, .lang-switch:focus-visible { text-decoration: underline; }
    h1 { font-size: clamp(1.4rem, 4vw, 1.8rem); line-height: 1.25; margin: 0 0 8px; }
    h2 { font-size: 1.2rem; margin: 32px 0 8px; }
    h3 { font-size: 1.02rem; margin: 20px 0 6px; }
    p, li { overflow-wrap: anywhere; }
    ul { padding-left: 1.25em; }
    em { color: var(--muted); }
  </style>
</head>
<body>
  <main class="card">
    <header>
      <img class="logo" src="/assets/realunit-logo.png" width="900" height="267" alt="RealUnit Schweiz AG" />
      <a class="lang-switch" href="${page.switchHref}" hreflang="${page.switchLang}" lang="${page.switchLang}">${page.switchLabel}</a>
    </header>
    <article>
${body}
    </article>
  </main>
</body>
</html>
`;
}

export function buildAll() {
  return Object.keys(PAGES).map((lang) => {
    const page = PAGES[lang];
    const markdown = readFileSync(join(ROOT, page.source), 'utf8');
    return { target: page.target, html: renderPage(lang, markdown) };
  });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const { target, html } of buildAll()) {
    const path = join(ROOT, target);
    if (check) {
      let current = '';
      try {
        current = readFileSync(path, 'utf8');
      } catch {
        current = '';
      }
      if (current !== html) {
        console.error(`${target} is out of date; run node scripts/build-privacy.mjs`);
        stale = true;
      }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, html);
      console.log(`wrote ${target}`);
    }
  }
  if (stale) process.exit(1);
}
